global:
  autoscaling: true

backend:
  cron:
    jobs:
      hmcrSync:
        schedule: "0 9 * * *"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
  ingress:
    host: wisr.apps.gold.devops.gov.bc.ca
    restrictMain: false
    restrictDocs: true
