global:
  autoscaling: true

backend:
  cron:
    jobs:
      hmcrSync:
        schedule: "0 9 * * *"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
  ingress:
    host: wisr.apps.gold.devops.gov.bc.ca
