/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health check endpoint
     * @description Returns the health status of the application. Used by Docker HEALTHCHECK and kubelet probes. Cluster-internal. Requests carrying x-forwarded-host, which the OpenShift router sets on all public traffic, receive 404.
     */
    get: operations['getHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/metrics': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Prometheus metrics exposition
     * @description Returns Prometheus metrics in exposition format. Cluster-internal. Requests carrying x-forwarded-host, which the OpenShift router sets on all public traffic, receive 404.
     */
    get: operations['getMetrics']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/incidents/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Query wildlife-vehicle incidents
     * @description Returns wildlife-vehicle collision incidents with optional filtering by species, service area, date range, spatial geometry, and more.
     */
    get: operations['getIncidents']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/incidents/filters': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get available incident filter options
     * @description Returns all available filter values for populating frontend dropdowns.
     */
    get: operations['getIncidentFilters']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/incidents/density': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get LKI segment density analysis
     * @description Returns incident counts per LKI segment with body-size weighting for linear heatmap visualization.
     */
    get: operations['getLkiDensity']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/service-areas/boundaries': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get service area boundary polygons
     * @description Returns simplified boundary geometries for all service areas as a GeoJSON FeatureCollection.
     */
    get: operations['getServiceAreaBoundaries']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/service-areas/lookup': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Look up service area by coordinates
     * @description Returns the service area containing the given point, or null if outside all boundaries.
     */
    get: operations['lookupServiceArea']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/route/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get a route between two points
     * @description Returns the road route between two points from the BC Route Planner as a GeoJSON LineString with distance and travel time.
     */
    get: operations['getRoute']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/internal/incidents/lki-sync': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Sync LKI highway segments from BC WFS
     * @description Fetches all LKI highway segments from the BC DataCatalogue WFS and upserts them into the local database using chris_lki_segment_id for deduplication. Cluster-internal. Requests carrying x-forwarded-host, which the OpenShift router sets on all public traffic, receive 404.
     */
    post: operations['syncLkiSegments']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/internal/incidents/hmcr-sync': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Sync wildlife incidents from HMCR
     * @description Fetches all wildlife records from the HMCR API and upserts them into the local database using hmcr_record_id for deduplication. Cluster-internal. Requests carrying x-forwarded-host, which the OpenShift router sets on all public traffic, receive 404.
     */
    post: operations['syncHmcrIncidents']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @description Application health status */
    HealthCheck: {
      /** @enum {string} */
      status: 'healthy' | 'unhealthy'
      /** Format: date-time */
      timestamp: string
      checks: {
        /** @enum {string} */
        database: 'ok' | 'failed'
      }
    }
    /** @description Paginated incident records */
    Incidents: {
      /** @description Result items */
      data: components['schemas']['Incident'][]
      /** @description Total matching records (before pagination) */
      total: number
      /** @description Requested page size (omitted when unbounded) */
      limit?: number
      /** @description Number of records skipped */
      offset: number
    }
    /** @description A wildlife-vehicle collision record */
    Incident: {
      id: number
      year: number
      accidentDate: string | null
      speciesId: number
      speciesName: string
      speciesColor: string
      speciesGroupName: string
      serviceAreaId: number | null
      serviceAreaName: string | null
      contractAreaNumber: number | null
      district: string | null
      region: string | null
      sex: components['schemas']['Sex'] | null
      timeOfKill: components['schemas']['TimeOfKill'] | null
      age: components['schemas']['Age'] | null
      quantity: number
      latitude: number | null
      longitude: number | null
      nearestTown: string | null
      comments: string
    }
    /**
     * @description Biological sex of the animal
     * @example MALE
     * @enum {string}
     */
    Sex: 'MALE' | 'FEMALE' | 'UNKNOWN'
    /**
     * @description Approximate time of day the incident occurred
     * @example DAY
     * @enum {string}
     */
    TimeOfKill: 'DAY' | 'DAWN' | 'DUSK' | 'DARK' | 'UNKNOWN'
    /**
     * @description Age classification of the animal
     * @example ADULT
     * @enum {string}
     */
    Age: 'ADULT' | 'YOUNG' | 'UNKNOWN'
    /** @description Standard error response */
    Error: {
      /** @description HTTP status code */
      statusCode: number
      /** @description HTTP status text */
      error: string
      /** @description Error detail, replaced with a generic string for 5xx */
      message: string
    }
    /** @description Available filter values across the incident dataset */
    IncidentFilters: {
      years: number[]
      species: components['schemas']['Species'][]
      serviceAreas: components['schemas']['ServiceArea'][]
      sex: components['schemas']['Sex'][]
      timeOfKill: components['schemas']['TimeOfKill'][]
      age: components['schemas']['Age'][]
      dateRange: {
        /** Format: date */
        min: string | null
        /** Format: date */
        max: string | null
      }
    }
    /** @description Wildlife species with display color and species group */
    Species: {
      id: number
      name: string
      color: string
      groupName: string
    }
    /** @description Highway maintenance service area */
    ServiceArea: {
      id: number
      name: string
      contractAreaNumber: number
      district: string
      region: string
    }
    /** @description Per-segment incident density for the current filters */
    LkiDensity: components['schemas']['DensitySegment'][]
    /** @description LKI highway segment with incident density counts */
    DensitySegment: {
      segmentId: number
      segmentName: string
      segmentDescription: string | null
      highwayNumber: string | null
      segmentLengthKm: number | null
      geometry: components['schemas']['LineGeometry']
      small: number
      medium: number
      large: number
      totalAnimals: number
      weighted: number
      densityPerKm: number | null
    }
    /** @description LineString or MultiLineString, discriminated on type */
    LineGeometry:
      | components['schemas']['LineString']
      | components['schemas']['MultiLineString']
    /** @description GeoJSON LineString, an ordered array of positions */
    LineString: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'LineString'
      coordinates: number[][]
    }
    /** @description GeoJSON MultiLineString, an array of LineString coordinate sets */
    MultiLineString: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'MultiLineString'
      coordinates: number[][][]
    }
    /** @description GeoJSON FeatureCollection of service area boundary polygons */
    ServiceAreaBoundaries: {
      /** @enum {string} */
      type: 'FeatureCollection'
      features: components['schemas']['BoundaryFeature'][]
    }
    /** @description GeoJSON Feature for one service area boundary */
    BoundaryFeature: {
      /** @enum {string} */
      type: 'Feature'
      geometry: components['schemas']['PolygonGeometry']
      properties: components['schemas']['ServiceArea']
    }
    /** @description Polygon or MultiPolygon, discriminated on type */
    PolygonGeometry:
      | components['schemas']['Polygon']
      | components['schemas']['MultiPolygon']
    /** @description GeoJSON Polygon, outer ring first followed by any holes */
    Polygon: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'Polygon'
      coordinates: number[][][]
    }
    /** @description GeoJSON MultiPolygon, an array of Polygon coordinate sets */
    MultiPolygon: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'MultiPolygon'
      coordinates: number[][][][]
    }
    /** @description Service area matching the given coordinates, or null if outside all boundaries */
    ServiceAreaLookup: components['schemas']['ServiceArea'] | null
    /** @description Road route between two points from the BC Route Planner */
    Route: {
      routeFound: boolean
      distance: number
      distanceUnit: string
      time: number
      timeText: string
      line: components['schemas']['LineString'] | null
    }
    /** @description Counts from an LKI segment sync run */
    LkiSyncResult: {
      totalFetched: number
      upserted: number
      deleted: number
      durationMs: number
    }
    /** @description Counts from an HMCR sync run */
    HmcrSyncResult: {
      created: number
      updated: number
      unchanged: number
      totalFetched: number
      errors: number
      durationMs: number
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthCheck']
        }
      }
      /** @description Rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Default Response */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthCheck']
        }
      }
    }
  }
  getMetrics: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Prometheus exposition format (text/plain) */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'text/plain; version=0.0.4; charset=utf-8': string
        }
      }
      /** @description Rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  getIncidents: {
    parameters: {
      query: {
        year: string
        species?: string
        serviceArea?: string
        sex?: string
        timeOfKill?: string
        age?: string
        /** @description Start date filter (inclusive, YYYY-MM-DD) */
        startDate?: string
        /** @description End date filter (inclusive, YYYY-MM-DD) */
        endDate?: string
        geometry?: string
        /** @description Route corridor filter: start point longitude */
        routeStartLng?: number
        /** @description Route corridor filter: start point latitude */
        routeStartLat?: number
        /** @description Route corridor filter: end point longitude */
        routeEndLng?: number
        /** @description Route corridor filter: end point latitude */
        routeEndLat?: number
        /** @description Route corridor filter: corridor width in metres */
        routeCorridorM?: number
        /** @description Max results to return (1-1000). Omit to fetch all. */
        limit?: number
        /** @description Number of results to skip (used with limit) */
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Incidents']
        }
      }
      /** @description Default Response */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Default Response */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Default Response */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Default Response */
      502: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  getIncidentFilters: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IncidentFilters']
        }
      }
      /** @description Rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Default Response */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  getLkiDensity: {
    parameters: {
      query: {
        year: string
        species?: string
        serviceArea?: string
        sex?: string
        timeOfKill?: string
        age?: string
        /** @description Start date filter (inclusive, YYYY-MM-DD) */
        startDate?: string
        /** @description End date filter (inclusive, YYYY-MM-DD) */
        endDate?: string
        geometry?: string
        /** @description Route corridor filter: start point longitude */
        routeStartLng?: number
        /** @description Route corridor filter: start point latitude */
        routeStartLat?: number
        /** @description Route corridor filter: end point longitude */
        routeEndLng?: number
        /** @description Route corridor filter: end point latitude */
        routeEndLat?: number
        /** @description Route corridor filter: corridor width in metres */
        routeCorridorM?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LkiDensity']
        }
      }
      /** @description Default Response */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Default Response */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Default Response */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Default Response */
      502: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  getServiceAreaBoundaries: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ServiceAreaBoundaries']
        }
      }
      /** @description Rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Default Response */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  lookupServiceArea: {
    parameters: {
      query: {
        /** @description Longitude (WGS 84) */
        lng: number
        /** @description Latitude (WGS 84) */
        lat: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ServiceAreaLookup']
        }
      }
      /** @description Default Response */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Default Response */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  getRoute: {
    parameters: {
      query: {
        /** @description Longitude of the route start point */
        startLng: number
        /** @description Latitude of the route start point */
        startLat: number
        /** @description Longitude of the route end point */
        endLng: number
        /** @description Latitude of the route end point */
        endLat: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Route']
        }
      }
      /** @description Default Response */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Default Response */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Default Response */
      502: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  syncLkiSegments: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LkiSyncResult']
        }
      }
      /** @description Rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Default Response */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  syncHmcrIncidents: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HmcrSyncResult']
        }
      }
      /** @description Rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Default Response */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
}
