/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Age = 'ADULT' | 'UNKNOWN' | 'YOUNG'

export type BodySize = 'LARGE' | 'MEDIUM' | 'SMALL'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Numeric = ColumnType<string, number | string, number | string>

export type Sex = 'FEMALE' | 'MALE' | 'UNKNOWN'

export type TimeOfKill = 'DARK' | 'DAWN' | 'DAY' | 'DUSK' | 'UNKNOWN'

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface GeographyColumns {
  coord_dimension: number | null
  f_geography_column: string | null
  f_table_catalog: string | null
  f_table_name: string | null
  f_table_schema: string | null
  srid: number | null
  type: string | null
}

export interface GeometryColumns {
  coord_dimension: number | null
  f_geometry_column: string | null
  f_table_catalog: string | null
  f_table_name: string | null
  f_table_schema: string | null
  srid: number | null
  type: string | null
}

export interface Incidents {
  accident_date: Timestamp | null
  age: Age | null
  comments: string | null
  created_at: Generated<Timestamp>
  geom: string | null
  hmcr_record_id: number | null
  id: Generated<number>
  latitude: Numeric | null
  lki_segment_id: number | null
  longitude: Numeric | null
  nearest_town: string | null
  quantity: Generated<number>
  service_area_id: number | null
  sex: Sex | null
  species_id: number
  time_of_kill: TimeOfKill | null
  updated_at: Generated<Timestamp>
  year: number
}

export interface LkiSegments {
  chris_lki_segment_id: number
  created_at: Generated<Timestamp>
  feature_length_m: Numeric | null
  geom: string
  highway_number: string | null
  lki_route_id: string | null
  lki_segment_description: string | null
  lki_segment_direction: string | null
  lki_segment_length: Numeric | null
  lki_segment_name: string
  objectid: number | null
  updated_at: Generated<Timestamp>
}

export interface ServiceAreas {
  contract_area_number: number
  created_at: Generated<Timestamp>
  district: string
  geom: string
  geom_simplified: string | null
  id: Generated<number>
  name: string
  region: string
  updated_at: Generated<Timestamp>
}

export interface SpatialRefSys {
  auth_name: string | null
  auth_srid: number | null
  proj4text: string | null
  srid: number
  srtext: string | null
}

export interface Species {
  body_size: Generated<BodySize>
  color: string
  group_name: string
  id: Generated<number>
  name: string
}

export interface DB {
  geography_columns: GeographyColumns
  geometry_columns: GeometryColumns
  incidents: Incidents
  lki_segments: LkiSegments
  service_areas: ServiceAreas
  spatial_ref_sys: SpatialRefSys
  species: Species
}
