name: PR

on:
  workflow_dispatch:
  #pull_request:

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  # https://github.com/bcgov/action-builder-ghcr
  builds:
    name: Builds
    permissions:
      packages: write
      id-token: write
      attestations: write
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [backend, migrations, seed]
        include:
          - package: backend
            build_context: .
            build_file: Dockerfile
            triggers: "('src/' 'package.json' 'bun.lock' 'vite.config.js' 'tsconfig.json' 'Dockerfile')"
          - package: migrations
            build_context: .
            build_file: Dockerfile.migrations
            triggers: "('migrations/' 'src/services/database/' 'Dockerfile.migrations')"
          - package: seed
            build_context: .
            build_file: Dockerfile.seed
            triggers: "('scripts/' 'src/services/database/' 'Dockerfile.seed' 'package.json' 'bun.lock')"
    timeout-minutes: 10
    steps:
      - uses: bcgov/action-builder-ghcr@de3d575cf158e16f5dc2789630f6d587483b911c # v4.4.0
        with:
          package: ${{ matrix.package }}
          build_context: ${{ matrix.build_context }}
          build_file: ${{ matrix.build_file }}
          tags: ${{ github.event.number }}
          tag_fallback: latest
          triggers: ${{ matrix.triggers }}

  deploys:
    name: Deploys (${{ github.event.number }})
    needs: [builds]
    uses: ./.github/workflows/.deployer.yml
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
      keycloak_url: ${{ secrets.KEYCLOAK_URL }}
      keycloak_realm: ${{ secrets.KEYCLOAK_REALM }}
      keycloak_client_id: ${{ secrets.KEYCLOAK_CLIENT_ID }}
      siteminder_logout_url: ${{ secrets.SITEMINDER_LOGOUT_URL }}
      hmcr_api_url: ${{ secrets.HMCR_API_URL }}
      hmcr_token_url: ${{ secrets.HMCR_TOKEN_URL }}
      hmcr_id: ${{ secrets.HMCR_ID }}
      hmcr_secret: ${{ secrets.HMCR_SECRET }}
      google_maps_client_api_key: ${{ secrets.GOOGLE_MAPS_CLIENT_API_KEY }}
      base_map_style_url: ${{ secrets.BASE_MAP_STYLE_URL }}
      seed_s3_endpoint_url: ${{ secrets.SEED_S3_ENDPOINT_URL }}
      seed_s3_bucket: ${{ secrets.SEED_S3_BUCKET }}
      seed_s3_access_key: ${{ secrets.SEED_S3_ACCESS_KEY }}
      seed_s3_secret_key: ${{ secrets.SEED_S3_SECRET_KEY }}
    with:
      db_user: app-${{ github.event.number }}
      backend_tag: ${{ github.event.number }}
      migrations_tag: ${{ github.event.number }}
      seed_tag: ${{ github.event.number }}
      params: --set global.secrets.persist=false
      db_triggers: ('charts/crunchy/')

  results:
    name: PR Results
    needs: [builds, deploys]
    if: always()
    runs-on: ubuntu-slim
    steps:
      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
        run: echo "At least one job has failed." && exit 1
      - run: echo "Success!"
